package com.remindly.ui.theme

import androidx.compose.runtime.staticCompositionLocalOf
import com.remindly.domain.model.AppLanguage

data class AppStrings(
    // Global & Navigation
    val appName: String,
    val back: String,
    val close: String,
    val cancel: String,
    val save: String,
    val delete: String,
    val edit: String,
    val understand: String,
    val error: String,
    val syncErrorTitle: String,
    val success: String,
    val confirm: String,

    // Onboarding Language Screen
    val onboardingWelcomeTitle: String,
    val onboardingWelcomeSubtitle: String,
    val onboardingLanguageDescription: String,
    val onboardingContinueButton: String,
    val selectLanguage: String,

    // Auth / Login Screen
    val loginSubtitle: String,
    val continueWithGoogle: String,
    val loginTerms: String,

    // Home Screen & Workspaces
    val homeTitle: String,
    val myWorkspace: String,
    val workspaceOf: (String) -> String,
    val personalWorkspace: String,
    val connectToWorkspace: String,
    val collaboratorsTitle: String,
    val noCollaborators: String,
    val newCollaboratorTitle: String,
    val collaboratorNameLabel: String,
    val collaboratorEmailLabel: String,
    val noRemindersTitle: String,
    val noRemindersSubtitle: String,
    val filterAll: String,
    val filterPlace: String,
    val filterTime: String,
    val filterCompleted: String,
    val newReminderFab: String,
    val createFirstReminder: String,
    val noTextPlaceholder: String,
    val moveUp: String,
    val moveDown: String,
    val nearbySectionTitle: String,
    val todaySectionTitle: String,
    val otherRemindersSectionTitle: String,
    val distanceMeters: (Int) -> String,
    val distanceKm: (Float) -> String,
    val audioPlayTooltip: String,
    val audioStopTooltip: String,
    val repeatingBadge: String,
    val diagnosticStart: String,
    val diagnosticStop: String,
    val diagnosticBadge: (String, Int) -> String,
    val diagnosticNotificationTitle: String,

    // Quick Capture Sheet & Dictation
    val quickShortcutsTitle: String,
    val shortcutHome: String,
    val shortcutWork: String,
    val shortcutSupermarket: String,
    val shortcutPharmacy: String,
    val shortcutThisEvening: String,
    val shortcutTomorrowMorning: String,
    val capturePlaceholder: String,
    val voiceDictationTooltip: String,
    val voiceDictationPrompt: String,
    val voiceDictationUnavailable: String,
    val voiceDictatedAdded: String,
    val categoryDetectedPrefix: String,
    val addTimeChip: String,
    val addPlaceChip: String,
    val removePlaceTooltip: String,
    val removeTimeTooltip: String,
    val photoChipEmpty: String,
    val photoChipCount: (Int) -> String,
    val validationEmptyError: String,
    val deleteRecording: String,

    // Categories
    val categorySupermarket: String,
    val categoryPharmacy: String,
    val categoryBakery: String,
    val categoryGasStation: String,
    val categoryAtm: String,
    val categoryRestaurant: String,
    val categoryAroundMe: String,
    val categoryOnCommute: String,

    // Place Picker & Detection Radius
    val placePickerTitle: String,
    val placePickerTabMap: String,
    val placePickerTabCategory: String,
    val placePickerSearchPlaceholder: String,
    val placePickerSelectedPoint: String,
    val placePickerConfirmButton: String,
    val detectionRadiusLabel: String,
    val radiusFormatMeters: (Int) -> String,
    val radiusFormatKm: (Float) -> String,
    val presetPedestrian: String,
    val presetStandard: String,
    val presetBroad: String,
    val presetTransit: String,
    val placeActivationTitle: String,
    val placeActivationImmediate: String,
    val placeActivationThisEvening: String,
    val placeActivationTomorrowMorning: String,
    val placeActivationCustomDate: String,
    val placeActivationActiveFrom: (String) -> String,
    val placeActivationClear: String,
    val placeActivationHint: String,
    val combinedTriggerBadge: String,
    val combinedTriggerExplanation: String,
    val waitingUntilBadge: (String) -> String,

    // Reminder Detail Screen
    val detailTitle: String,
    val reminderTextLabel: String,
    val setTime: String,
    val setPlace: String,
    val addImage: String,
    val attachedImages: String,
    val voiceNote: String,
    val sentBy: (String) -> String,
    val completeReminder: String,
    val recurrenceSectionTitle: String,
    val recurrenceOnce: String,
    val recurrenceOnceSubtitle: String,
    val recurrenceHabit: String,
    val recurrenceHabitSubtitle: String,

    // Settings Screen
    val settingsTitle: String,
    // Section Langue
    val settingsLanguageSectionTitle: String,
    val settingsLanguageSectionSubtitle: String,
    val settingsLanguageCurrent: String,
    // Section Rappels Vocaux
    val settingsVoiceSectionTitle: String,
    val settingsVoiceSectionSubtitle: String,
    val settingsVolume: String,
    val settingsTestVolume: String,
    val settingsStopVolumeTest: String,
    val settingsRepeatAudio: String,
    val settingsRepeatSubtitle: String,
    val settingsRepeatOnce: String,
    val settingsRepeatTwice: String,
    val settingsRepeatThrice: String,
    val settingsRepeat5Times: String,
    val settingsRepeatLoop: String,
    val settingsRepeatLoopWarning: String,
    val settingsVibration: String,
    val settingsVibrationSubtitle: String,
    val settingsAnnouncePlace: String,
    val settingsAnnouncePlaceSubtitle: String,
    val settingsReadTextAloud: String,
    val settingsReadTextAloudSubtitle: String,
    // Section Trajet & Périmètre
    val settingsCommuteSectionTitle: String,
    val settingsCommuteSectionSubtitle: String,
    val settingsMyCommuteRoute: String,
    val settingsCommuteNotConfigured: String,
    val settingsTraceRoute: String,
    val settingsModifyRoute: String,
    val settingsClearRoute: String,
    val settingsPoiDetectionRadius: String,
    val settingsPoiDetectionRadiusSubtitle: String,
    val settingsPoiGlobalSearchRadius: String,
    val settingsPoiGlobalSearchRadiusSubtitle: String,
    val settingsRollingExitRadius: String,
    val settingsRollingExitRadiusSubtitle: String,
    val settingsGeofenceCooldown: String,
    val settingsGeofenceCooldownSubtitle: String,
    val settingsSmartFilter: String,
    val settingsSmartFilterSubtitle: String,
    val settingsSmartFilterSpeedThreshold: String,
    val settingsSmartFilterSpeedThresholdSubtitle: String,
    // Section Canaux Système & Diagnostic & Compte
    val settingsSystemChannelsSectionTitle: String,
    val settingsSystemChannelsSectionSubtitle: String,
    val settingsChannelTimeTitle: String,
    val settingsChannelTimeSubtitle: String,
    val settingsChannelPlaceTitle: String,
    val settingsChannelPlaceSubtitle: String,
    val settingsLogsSectionTitle: String,
    val settingsLogsSectionSubtitle: String,
    val settingsViewLogs: String,
    val settingsViewLogsSubtitle: String,
    val settingsAccountSectionTitle: String,
    val settingsAccountSectionSubtitle: String,
    val settingsConnectedAs: String,
    val settingsNotConnected: String,
    val settingsLogout: String,
    val settingsLogoutConfirmTitle: String,
    val settingsLogoutConfirmMessage: String
)

val FrenchStrings = AppStrings(
    appName = "Remindly",
    back = "Retour",
    close = "Fermer",
    cancel = "Annuler",
    save = "Enregistrer",
    delete = "Supprimer",
    edit = "Modifier",
    understand = "Compris",
    error = "Erreur",
    syncErrorTitle = "Erreur de synchronisation",
    success = "Succès",
    confirm = "Confirmer",

    onboardingWelcomeTitle = "Bienvenue sur Remindly",
    onboardingWelcomeSubtitle = "Vos rappels contextuels intelligents au bon endroit, au bon moment",
    onboardingLanguageDescription = "Choisissez la langue de votre interface et de votre reconnaissance vocale :",
    onboardingContinueButton = "Continuer",
    selectLanguage = "Choisir la langue",

    loginSubtitle = "Vos rappels, partout et ensemble.",
    continueWithGoogle = "Continuer avec Google",
    loginTerms = "En continuant, vous acceptez nos\nConditions d'utilisation",

    homeTitle = "Mes Rappels",
    myWorkspace = "Mon Espace",
    workspaceOf = { email -> "Espace de $email" },
    personalWorkspace = "Mon Espace (Personnel)",
    connectToWorkspace = "Se connecter à un espace...",
    collaboratorsTitle = "Mes Collaborateurs",
    noCollaborators = "Aucun collaborateur enregistré.",
    newCollaboratorTitle = "Nouveau collaborateur",
    collaboratorNameLabel = "Nom (ex: Maman)",
    collaboratorEmailLabel = "Adresse E-mail",
    noRemindersTitle = "Aucun rappel",
    noRemindersSubtitle = "Appuyez sur + pour créer votre premier rappel vocal ou géographique",
    filterAll = "Tous",
    filterPlace = "Lieux",
    filterTime = "Heures",
    filterCompleted = "Terminés",
    newReminderFab = "Ajouter",
    createFirstReminder = "Créer un rappel",
    noTextPlaceholder = "(Sans texte)",
    moveUp = "Monter",
    moveDown = "Descendre",
    nearbySectionTitle = "🎯 À proximité en ce moment (< 2 km)",
    todaySectionTitle = "📅 Aujourd'hui",
    otherRemindersSectionTitle = "📋 Autres rappels",
    distanceMeters = { m -> "$m m" },
    distanceKm = { km -> String.format(java.util.Locale.ROOT, "%.1f km", km) },
    audioPlayTooltip = "Écouter la note vocale",
    audioStopTooltip = "Arrêter la lecture",
    repeatingBadge = "Habitude",
    diagnosticStart = "Diagnostiquer la distance",
    diagnosticStop = "Arrêter le suivi",
    diagnosticBadge = { dist, acc -> "📡 Suivi 5s : $dist (±$acc m)" },
    diagnosticNotificationTitle = "Surveillance intensive (Diagnostic)",

    quickShortcutsTitle = "Raccourcis rapides",
    shortcutHome = "Maison",
    shortcutWork = "Travail",
    shortcutSupermarket = "Supérette",
    shortcutPharmacy = "Pharmacie",
    shortcutThisEvening = "Ce soir 19h",
    shortcutTomorrowMorning = "Demain 8h30",
    capturePlaceholder = "Se rappeler de… ou appuyez sur le micro",
    voiceDictationTooltip = "Dictée vocale rapide",
    voiceDictationPrompt = "Dictez votre rappel (ex: Acheter du pain à la boulangerie)...",
    voiceDictationUnavailable = "Reconnaissance vocale non disponible",
    voiceDictatedAdded = "Texte dicté ajouté",
    categoryDetectedPrefix = "Catégorie détectée : ",
    addTimeChip = "Ajouter une heure",
    addPlaceChip = "Ajouter un lieu",
    removePlaceTooltip = "Supprimer le lieu",
    removeTimeTooltip = "Supprimer l'heure",
    photoChipEmpty = "Image",
    photoChipCount = { count -> "$count image(s)" },
    validationEmptyError = "Veuillez entrer un texte, un enregistrement audio ou une photo.",
    deleteRecording = "Supprimer l'enregistrement",

    categorySupermarket = "Supérette / Supermarché",
    categoryPharmacy = "Pharmacie",
    categoryBakery = "Boulangerie",
    categoryGasStation = "Station-service",
    categoryAtm = "Distributeur / Banque",
    categoryRestaurant = "Café / Restaurant",
    categoryAroundMe = "Autour de ma position",
    categoryOnCommute = "Sur mon trajet habituel",

    placePickerTitle = "Sélectionner un lieu",
    placePickerTabMap = "📍 Sur la carte",
    placePickerTabCategory = "🏷️ Par catégorie",
    placePickerSearchPlaceholder = "Rechercher une adresse, un commerce…",
    placePickerSelectedPoint = "Point sélectionné",
    placePickerConfirmButton = "Confirmer ce lieu",
    detectionRadiusLabel = "Rayon de détection",
    radiusFormatMeters = { m -> "$m m" },
    radiusFormatKm = { km -> String.format(java.util.Locale.ROOT, "%.1f km", km) },
    presetPedestrian = "🚶 150m (Piéton)",
    presetStandard = "🚗 450m (Standard)",
    presetBroad = "🛣️ 1 km (Large)",
    presetTransit = "🚆 2.5 km (Transit)",
    placeActivationTitle = "Actif à partir de (optionnel)",
    placeActivationImmediate = "Dès maintenant",
    placeActivationThisEvening = "Ce soir 18h",
    placeActivationTomorrowMorning = "Demain 08h",
    placeActivationCustomDate = "Date & heure…",
    placeActivationActiveFrom = { time -> "Actif dès : $time" },
    placeActivationClear = "Effacer",
    placeActivationHint = "Le rappel ne sonnera au lieu qu'à partir de cette heure.",
    combinedTriggerBadge = "Au 1er événement : Lieu OU Échéance",
    combinedTriggerExplanation = "Se déclenche au passage au lieu OU au plus tard à l'échéance (l'un annule l'autre).",
    waitingUntilBadge = { time -> "En attente jusqu'à $time" },

    detailTitle = "Détails du rappel",
    reminderTextLabel = "Texte du rappel",
    setTime = "Définir une heure",
    setPlace = "Définir un lieu",
    addImage = "Ajouter image",
    attachedImages = "Images jointes :",
    voiceNote = "Note vocale :",
    sentBy = { name -> "Envoyé par : $name" },
    completeReminder = "Terminer",
    recurrenceSectionTitle = "Fréquence du rappel",
    recurrenceOnce = "Une seule fois",
    recurrenceOnceSubtitle = "Désactive le rappel dès qu'il a sonné.",
    recurrenceHabit = "À chaque passage (Habitude)",
    recurrenceHabitSubtitle = "Reste actif indéfiniment pour vous avertir à chaque fois que vous êtes à proximité.",

    settingsTitle = "Paramètres",
    settingsLanguageSectionTitle = "Langue de l'application",
    settingsLanguageSectionSubtitle = "Personnalisez la langue d'affichage et de saisie vocale",
    settingsLanguageCurrent = "Langue active",

    settingsVoiceSectionTitle = "Rappels Vocaux",
    settingsVoiceSectionSubtitle = "Personnalisez la sonnerie pour vos enregistrements audio",
    settingsVolume = "Volume sonore",
    settingsTestVolume = "Tester le volume",
    settingsStopVolumeTest = "Arrêter le test",
    settingsRepeatAudio = "Répétition audio",
    settingsRepeatSubtitle = "Nombre de diffusions de l'enregistrement",
    settingsRepeatOnce = "1 fois",
    settingsRepeatTwice = "2 fois",
    settingsRepeatThrice = "3 fois",
    settingsRepeat5Times = "5 fois",
    settingsRepeatLoop = "En boucle",
    settingsRepeatLoopWarning = "L'audio tournera en continu jusqu'à ce que vous appuyiez sur « Arrêter » dans la notification.",
    settingsVibration = "Vibration",
    settingsVibrationSubtitle = "Vibrer pendant la sonnerie vocale",
    settingsAnnouncePlace = "Annoncer le lieu par voix",
    settingsAnnouncePlaceSubtitle = "Prononce le nom du commerce détecté (ex: « À proximité de Family Shop »)",
    settingsReadTextAloud = "Lire les rappels texte à voix haute",
    settingsReadTextAloudSubtitle = "Utilise la synthèse vocale pour lire le rappel si aucun enregistrement vocal n'est présent",

    settingsCommuteSectionTitle = "Trajet & Périmètre des Lieux",
    settingsCommuteSectionSubtitle = "Configuration pour les rappels par catégorie (supérettes, etc.)",
    settingsMyCommuteRoute = "Mon trajet habituel",
    settingsCommuteNotConfigured = "Non configuré (Départ ➔ Arrivée sur la carte)",
    settingsTraceRoute = "Tracer",
    settingsModifyRoute = "Modifier",
    settingsClearRoute = "Effacer",
    settingsPoiDetectionRadius = "Rayon de détection des commerces",
    settingsPoiDetectionRadiusSubtitle = "Taille de la zone circulaire autour de chaque commerce (POIs)",
    settingsPoiGlobalSearchRadius = "Périmètre de recherche globale POI",
    settingsPoiGlobalSearchRadiusSubtitle = "Rayon maximal autour de vous pour trouver les commerces sur Google Places",
    settingsRollingExitRadius = "Zone tampon de sortie (Fenêtre glissante)",
    settingsRollingExitRadiusSubtitle = "Distance parcourue en voiture avant d'actualiser automatiquement les commerces devant vous",
    settingsGeofenceCooldown = "Délai anti-rebond entre alertes",
    settingsGeofenceCooldownSubtitle = "Temps d'attente minimal avant de refaire sonner le rappel pour un commerce voisin",
    settingsSmartFilter = "Filtre intelligent d'accessibilité",
    settingsSmartFilterSubtitle = "Ignore les commerces hors d'atteinte (vitesse de voie rapide/autoroute ou sens opposé)",
    settingsSmartFilterSpeedThreshold = "Vitesse seuil de transit rapide",
    settingsSmartFilterSpeedThresholdSubtitle = "Au-delà de cette vitesse, les alertes pour commerces de proximité sont filtrées",

    settingsSystemChannelsSectionTitle = "Notifications Système",
    settingsSystemChannelsSectionSubtitle = "Sonneries par défaut pour les rappels sans voix",
    settingsChannelTimeTitle = "Canal Rappels Programmés (Temps)",
    settingsChannelTimeSubtitle = "Sonnerie, voyant et pop-up pour les heures",
    settingsChannelPlaceTitle = "Canal Rappels Géolocalisés (Lieu)",
    settingsChannelPlaceSubtitle = "Sonnerie, voyant et pop-up pour le GPS",
    settingsLogsSectionTitle = "Diagnostic & Journal (Logs)",
    settingsLogsSectionSubtitle = "Historique technique et traçabilité du cycle de vie des rappels",
    settingsViewLogs = "Voir le journal des événements (Logs)",
    settingsViewLogsSubtitle = "Consulter les étapes de création, POIs, armements et déclenchements",
    settingsAccountSectionTitle = "Compte & Session",
    settingsAccountSectionSubtitle = "Gestion de votre profil Remindly",
    settingsConnectedAs = "Connecté en tant que",
    settingsNotConnected = "Non connecté",
    settingsLogout = "Déconnexion",
    settingsLogoutConfirmTitle = "Se déconnecter ?",
    settingsLogoutConfirmMessage = "Vous devrez vous reconnecter pour synchroniser vos rappels."
)

val ArabicStrings = AppStrings(
    appName = "Remindly",
    back = "رجوع",
    close = "إغلاق",
    cancel = "إلغاء",
    save = "حفظ",
    delete = "حذف",
    edit = "تعديل",
    understand = "فهمت",
    error = "خطأ",
    syncErrorTitle = "خطأ في المزامنة",
    success = "تم بنجاح",
    confirm = "تأكيد",

    onboardingWelcomeTitle = "مرحباً بك في Remindly",
    onboardingWelcomeSubtitle = "تذكيراتك السياقية الذكية في المكان المناسب والوقت المناسب",
    onboardingLanguageDescription = "اختر لغة الواجهة والتعرف الصوتي المفضلة لديك:",
    onboardingContinueButton = "متابعة",
    selectLanguage = "اختيار اللغة",

    loginSubtitle = "تذكيراتك الذكية، في كل مكان ومعاً.",
    continueWithGoogle = "المتابعة باستخدام Google",
    loginTerms = "بالمتابعة، فإنك توافق على\nشروط الاستخدام",

    homeTitle = "تذكيراتي",
    myWorkspace = "مساحتي",
    workspaceOf = { email -> "مساحة $email" },
    personalWorkspace = "مساحتي (الشخصية)",
    connectToWorkspace = "الاتصال بمساحة...",
    collaboratorsTitle = "المشاركون",
    noCollaborators = "لا يوجد مشاركون مسجلون.",
    newCollaboratorTitle = "مشارك جديد",
    collaboratorNameLabel = "الاسم (مثال: أمي)",
    collaboratorEmailLabel = "البريد الإلكتروني",
    noRemindersTitle = "لا توجد تذكيرات",
    noRemindersSubtitle = "اضغط على زر + لإنشاء تذكيرك الصوتي أو الجغرافي الأول",
    filterAll = "الكل",
    filterPlace = "الأماكن",
    filterTime = "المواعيد",
    filterCompleted = "المكتملة",
    newReminderFab = "إضافة",
    createFirstReminder = "إنشاء تذكير",
    noTextPlaceholder = "(بدون نص)",
    moveUp = "للأعلى",
    moveDown = "للأسفل",
    nearbySectionTitle = "🎯 قريب منك الآن (< 2 كم)",
    todaySectionTitle = "📅 اليوم",
    otherRemindersSectionTitle = "📋 تذكيرات أخرى",
    distanceMeters = { m -> "$m م" },
    distanceKm = { km -> String.format(java.util.Locale.ROOT, "%.1f كم", km) },
    audioPlayTooltip = "تشغيل التسجيل الصوتي",
    audioStopTooltip = "إيقاف التشغيل",
    repeatingBadge = "عادة",
    diagnosticStart = "تشخيص المسافة",
    diagnosticStop = "إيقاف المتابعة",
    diagnosticBadge = { dist, acc -> "📡 متابعة 5 ث : $dist (±$acc م)" },
    diagnosticNotificationTitle = "متابعة مكثفة (تشخيص)",

    quickShortcutsTitle = "اختصارات سريعة",
    shortcutHome = "المنزل",
    shortcutWork = "العمل",
    shortcutSupermarket = "سوبيرات",
    shortcutPharmacy = "صيدلية",
    shortcutThisEvening = "هذا المساء 19:00",
    shortcutTomorrowMorning = "غداً 8:30",
    capturePlaceholder = "تذكر أن... أو اضغط على الميكروفون للتحدث",
    voiceDictationTooltip = "تسجيل صوتي سريع",
    voiceDictationPrompt = "تكلم لتسجيل التذكير (مثال: نشري الخبز مالكوشة أو دواء من لافارماسي)...",
    voiceDictationUnavailable = "التعرف الصوتي غير متوفر على هذا الجهاز",
    voiceDictatedAdded = "تمت إضافة النص المنطوق",
    categoryDetectedPrefix = "تم تحديد الفئة: ",
    addTimeChip = "إضافة موعد",
    addPlaceChip = "إضافة مكان",
    removePlaceTooltip = "حذف المكان",
    removeTimeTooltip = "حذف الموعد",
    photoChipEmpty = "صورة",
    photoChipCount = { count -> "$count صورة" },
    validationEmptyError = "يرجى كتابة نص، أو تسجيل صوت، أو إرفاق صورة.",
    deleteRecording = "حذف التسجيل",

    categorySupermarket = "سوبيرات / بقالة",
    categoryPharmacy = "صيدلية",
    categoryBakery = "مخبزة / كوشة",
    categoryGasStation = "محطة وقود / بومبة",
    categoryAtm = "صراف آلي / بنك",
    categoryRestaurant = "مطعم / مقهى",
    categoryAroundMe = "حول موقعي الحالي",
    categoryOnCommute = "على مسار طريقي اليومي",

    placePickerTitle = "تحديد موقع",
    placePickerTabMap = "📍 على الخريطة",
    placePickerTabCategory = "🏷️ حسب الفئة",
    placePickerSearchPlaceholder = "ابحث عن عنوان أو متجر…",
    placePickerSelectedPoint = "النقطة المحددة",
    placePickerConfirmButton = "تأكيد هذا المكان",
    detectionRadiusLabel = "نطاق التنبيه الجغرافي",
    radiusFormatMeters = { m -> "$m م" },
    radiusFormatKm = { km -> String.format(java.util.Locale.ROOT, "%.1f كم", km) },
    presetPedestrian = "🚶 150م (مشاة)",
    presetStandard = "🚗 450م (افتراضي)",
    presetBroad = "🛣️ 1 كم (واسع)",
    presetTransit = "🚆 2.5 كم (قطار/سفر)",
    placeActivationTitle = "تفعيل بدءاً من (اختياري)",
    placeActivationImmediate = "من الآن",
    placeActivationThisEvening = "هذا المساء 18:00",
    placeActivationTomorrowMorning = "غداً 08:00",
    placeActivationCustomDate = "تاريخ ووقت…",
    placeActivationActiveFrom = { time -> "مفعّل بدءاً من: $time" },
    placeActivationClear = "مسح",
    placeActivationHint = "لن ينبهك التذكير في هذا المكان إلا ابتداءً من هذا الوقت.",
    combinedTriggerBadge = "عند أول حدث: المكان أو الموعد الأقصى",
    combinedTriggerExplanation = "يتم التنبيه عند الوصول للمكان أو كحد أقصى في الموعد المحدد (أحدهما يلغي الآخر).",
    waitingUntilBadge = { time -> "قيد الانتظار حتى $time" },

    detailTitle = "تفاصيل التذكير",
    reminderTextLabel = "نص التذكير",
    setTime = "تحديد موعد",
    setPlace = "تحديد مكان",
    addImage = "إضافة صورة",
    attachedImages = "الصور المرفقة:",
    voiceNote = "التسجيل الصوتي:",
    sentBy = { name -> "مرسل من: $name" },
    completeReminder = "إكمال",
    recurrenceSectionTitle = "تكرار التنبيه",
    recurrenceOnce = "مرة واحدة فقط",
    recurrenceOnceSubtitle = "إيقاف التذكير تلقائياً بعد أول تنبيه.",
    recurrenceHabit = "كلما مررت بهذا المكان (عادة)",
    recurrenceHabitSubtitle = "يبقى مفعلاً باستمرار لتنبيهك في كل مرة تكون قريباً فيها.",

    settingsTitle = "الإعدادات",
    settingsLanguageSectionTitle = "لغة التطبيق",
    settingsLanguageSectionSubtitle = "تخصيص لغة العرض والأوامر الصوتية",
    settingsLanguageCurrent = "اللغة المفعلة",

    settingsVoiceSectionTitle = "التنبيهات الصوتية",
    settingsVoiceSectionSubtitle = "تخصيص نغمة ورنين التسجيلات الصوتية",
    settingsVolume = "مستوى الصوت",
    settingsTestVolume = "تجربة الصوت",
    settingsStopVolumeTest = "إيقاف التجربة",
    settingsRepeatAudio = "تكرار الصوت",
    settingsRepeatSubtitle = "عدد مرات إعادة تشغيل التسجيل الصوتي",
    settingsRepeatOnce = "مرة واحدة",
    settingsRepeatTwice = "مرتان",
    settingsRepeatThrice = "3 مرات",
    settingsRepeat5Times = "5 مرات",
    settingsRepeatLoop = "تكرار مستمر",
    settingsRepeatLoopWarning = "سيعمل التنبيه باستمرار حتى تضغط على « إيقاف » في الإشعار.",
    settingsVibration = "الاهتزاز",
    settingsVibrationSubtitle = "الاهتزاز أثناء التنبيه الصوتي",
    settingsAnnouncePlace = "نطق اسم المكان صوتياً",
    settingsAnnouncePlaceSubtitle = "ينطق اسم المحل المكتشف (مثال: « بالقرب من محطة نفطال »)",
    settingsReadTextAloud = "قراءة التذكيرات النصية بصوت مسموع",
    settingsReadTextAloudSubtitle = "استخدام القارئ الآلي لنطق التذكير إذا لم يتوفر تسجيل صوتي",

    settingsCommuteSectionTitle = "المسار اليومي ونطاق الأماكن",
    settingsCommuteSectionSubtitle = "إعدادات التذكيرات حسب الفئة (سوبيرات، صيدليات...)",
    settingsMyCommuteRoute = "مسار طريقي المعتاد",
    settingsCommuteNotConfigured = "غير محدد (الانطلاق ➔ الوصول على الخريطة)",
    settingsTraceRoute = "رسم المسار",
    settingsModifyRoute = "تعديل",
    settingsClearRoute = "مسح",
    settingsPoiDetectionRadius = "نطاق اكتشاف المحلات",
    settingsPoiDetectionRadiusSubtitle = "حجم المنطقة الدائرية حول كل محل تجاري",
    settingsPoiGlobalSearchRadius = "نطاق البحث الجغرافي الشامل",
    settingsPoiGlobalSearchRadiusSubtitle = "المسافة القصوى حولك للبحث عن المحلات في Google Places",
    settingsRollingExitRadius = "النافذة المتحركة (تحديث المسار)",
    settingsRollingExitRadiusSubtitle = "المسافة المقطوعة بالسيارة قبل تحديث المحلات أمامك تلقائياً",
    settingsGeofenceCooldown = "مهلة منع التكرار المتقارب",
    settingsGeofenceCooldownSubtitle = "الحد الأدنى للوقت قبل إعادة التنبيه لنفس التذكير عند محل مجاور",
    settingsSmartFilter = "الفلتر الذكي للوصول والأمان",
    settingsSmartFilterSubtitle = "تجاهل المحلات غير القابلة للوصول (السرعة العالية على الطرق السريعة أو الاتجاه المعاكس)",
    settingsSmartFilterSpeedThreshold = "سرعة المرور السريع",
    settingsSmartFilterSpeedThresholdSubtitle = "فوق هذه السرعة، يتم تصفية التنبيهات الخاصة بالمحلات لتفادي الإزعاج أثناء القيادة السريعة",

    settingsSystemChannelsSectionTitle = "إشعارات النظام",
    settingsSystemChannelsSectionSubtitle = "النغمات الافتراضية للتذكيرات بدون صوت",
    settingsChannelTimeTitle = "قناة المواعيد المجدولة",
    settingsChannelTimeSubtitle = "النغمة والضوء والنافذة المنبثقة للوقت",
    settingsChannelPlaceTitle = "قناة التذكيرات الجغرافية (المكان)",
    settingsChannelPlaceSubtitle = "النغمة والضوء والنافذة المنبثقة لموقع GPS",
    settingsLogsSectionTitle = "سجل التشخيص والتتبع",
    settingsLogsSectionSubtitle = "السجل التقني الشامل لتتبع دورة حياة التذكيرات",
    settingsViewLogs = "عرض سجل الأحداث التقني",
    settingsViewLogsSubtitle = "مراجعة خطوات الإنشاء، المحلات، التسليح، والتنبيهات",
    settingsAccountSectionTitle = "الحساب والجلسة",
    settingsAccountSectionSubtitle = "إدارة ملفك الشخصي في Remindly",
    settingsConnectedAs = "مسجل الدخول بحساب",
    settingsNotConnected = "غير متصل",
    settingsLogout = "تسجيل الخروج",
    settingsLogoutConfirmTitle = "هل تريد تسجيل الخروج؟",
    settingsLogoutConfirmMessage = "ستحتاج إلى تسجيل الدخول مجدداً لمزامنة تذكيراتك."
)

val EnglishStrings = AppStrings(
    appName = "Remindly",
    back = "Back",
    close = "Close",
    cancel = "Cancel",
    save = "Save",
    delete = "Delete",
    edit = "Edit",
    understand = "Got it",
    error = "Error",
    syncErrorTitle = "Sync Error",
    success = "Success",
    confirm = "Confirm",

    onboardingWelcomeTitle = "Welcome to Remindly",
    onboardingWelcomeSubtitle = "Smart contextual reminders at the right place, at the right time",
    onboardingLanguageDescription = "Choose your preferred interface and voice recognition language:",
    onboardingContinueButton = "Continue",
    selectLanguage = "Select Language",

    loginSubtitle = "Your reminders, everywhere and together.",
    continueWithGoogle = "Continue with Google",
    loginTerms = "By continuing, you agree to our\nTerms of Service",

    homeTitle = "My Reminders",
    myWorkspace = "My Workspace",
    workspaceOf = { email -> "$email's Workspace" },
    personalWorkspace = "My Workspace (Personal)",
    connectToWorkspace = "Connect to a workspace...",
    collaboratorsTitle = "My Collaborators",
    noCollaborators = "No collaborators registered.",
    newCollaboratorTitle = "New Collaborator",
    collaboratorNameLabel = "Name (e.g., Mom)",
    collaboratorEmailLabel = "Email address",
    noRemindersTitle = "No reminders",
    noRemindersSubtitle = "Tap + to create your first voice or location reminder",
    filterAll = "All",
    filterPlace = "Places",
    filterTime = "Times",
    filterCompleted = "Completed",
    newReminderFab = "Add",
    createFirstReminder = "Create reminder",
    noTextPlaceholder = "(No text)",
    moveUp = "Move up",
    moveDown = "Move down",
    nearbySectionTitle = "🎯 Nearby right now (< 2 km)",
    todaySectionTitle = "📅 Today",
    otherRemindersSectionTitle = "📋 Other reminders",
    distanceMeters = { m -> "$m m" },
    distanceKm = { km -> String.format(java.util.Locale.ROOT, "%.1f km", km) },
    audioPlayTooltip = "Play voice note",
    audioStopTooltip = "Stop audio",
    repeatingBadge = "Habit",
    diagnosticStart = "Diagnose distance",
    diagnosticStop = "Stop tracking",
    diagnosticBadge = { dist, acc -> "📡 Live 5s: $dist (±$acc m)" },
    diagnosticNotificationTitle = "Intensive tracking (Diagnostic)",

    quickShortcutsTitle = "Quick shortcuts",
    shortcutHome = "Home",
    shortcutWork = "Work",
    shortcutSupermarket = "Grocery",
    shortcutPharmacy = "Pharmacy",
    shortcutThisEvening = "Tonight 7 PM",
    shortcutTomorrowMorning = "Tomorrow 8:30 AM",
    capturePlaceholder = "Remind me to… or tap the mic",
    voiceDictationTooltip = "Quick voice dictation",
    voiceDictationPrompt = "Dictate your reminder (e.g., Buy bread at bakery)...",
    voiceDictationUnavailable = "Voice recognition not available",
    voiceDictatedAdded = "Dictated text added",
    categoryDetectedPrefix = "Detected category: ",
    addTimeChip = "Add a time",
    addPlaceChip = "Add a place",
    removePlaceTooltip = "Remove place",
    removeTimeTooltip = "Remove time",
    photoChipEmpty = "Image",
    photoChipCount = { count -> "$count image(s)" },
    validationEmptyError = "Please enter text, a voice recording, or a photo.",
    deleteRecording = "Delete recording",

    categorySupermarket = "Supermarket / Grocery",
    categoryPharmacy = "Pharmacy",
    categoryBakery = "Bakery",
    categoryGasStation = "Gas station",
    categoryAtm = "ATM / Bank",
    categoryRestaurant = "Cafe / Restaurant",
    categoryAroundMe = "Around my location",
    categoryOnCommute = "On my usual commute",

    placePickerTitle = "Select a location",
    placePickerTabMap = "📍 On map",
    placePickerTabCategory = "🏷️ By category",
    placePickerSearchPlaceholder = "Search address, shop…",
    placePickerSelectedPoint = "Selected point",
    placePickerConfirmButton = "Confirm this location",
    detectionRadiusLabel = "Detection radius",
    radiusFormatMeters = { m -> "$m m" },
    radiusFormatKm = { km -> String.format(java.util.Locale.ROOT, "%.1f km", km) },
    presetPedestrian = "🚶 150m (Walking)",
    presetStandard = "🚗 450m (Standard)",
    presetBroad = "🛣️ 1 km (Broad)",
    presetTransit = "🚆 2.5 km (Transit)",
    placeActivationTitle = "Active from (optional)",
    placeActivationImmediate = "Right now",
    placeActivationThisEvening = "This evening 6 PM",
    placeActivationTomorrowMorning = "Tomorrow 8 AM",
    placeActivationCustomDate = "Date & time…",
    placeActivationActiveFrom = { time -> "Active from: $time" },
    placeActivationClear = "Clear",
    placeActivationHint = "The reminder will only trigger at this location starting from this time.",
    combinedTriggerBadge = "First event: Place OR Deadline",
    combinedTriggerExplanation = "Triggers upon arriving at the location OR at the latest deadline (whichever happens first cancels the other).",
    waitingUntilBadge = { time -> "Waiting until $time" },

    detailTitle = "Reminder Details",
    reminderTextLabel = "Reminder text",
    setTime = "Set time",
    setPlace = "Set place",
    addImage = "Add image",
    attachedImages = "Attached images:",
    voiceNote = "Voice note:",
    sentBy = { name -> "Sent by: $name" },
    completeReminder = "Complete",
    recurrenceSectionTitle = "Reminder frequency",
    recurrenceOnce = "Once only",
    recurrenceOnceSubtitle = "Deactivates the reminder after first trigger.",
    recurrenceHabit = "Every visit (Habit)",
    recurrenceHabitSubtitle = "Stays active to notify you whenever you are nearby.",

    settingsTitle = "Settings",
    settingsLanguageSectionTitle = "App Language",
    settingsLanguageSectionSubtitle = "Customize display language and voice dictation recognition",
    settingsLanguageCurrent = "Active Language",

    settingsVoiceSectionTitle = "Voice Reminders",
    settingsVoiceSectionSubtitle = "Customize alert chime and playback for your audio recordings",
    settingsVolume = "Sound Volume",
    settingsTestVolume = "Test volume",
    settingsStopVolumeTest = "Stop test",
    settingsRepeatAudio = "Audio Repetition",
    settingsRepeatSubtitle = "Number of times the recording plays",
    settingsRepeatOnce = "1 time",
    settingsRepeatTwice = "2 times",
    settingsRepeatThrice = "3 times",
    settingsRepeat5Times = "5 times",
    settingsRepeatLoop = "Loop continuously",
    settingsRepeatLoopWarning = "Audio will loop continuously until you tap 'Stop' in the notification.",
    settingsVibration = "Vibration",
    settingsVibrationSubtitle = "Vibrate during voice alarm",
    settingsAnnouncePlace = "Announce place name by voice",
    settingsAnnouncePlaceSubtitle = "Speaks the detected place name (e.g., 'Nearby Family Shop')",
    settingsReadTextAloud = "Read text reminders aloud",
    settingsReadTextAloudSubtitle = "Uses text-to-speech if no voice recording is present",

    settingsCommuteSectionTitle = "Commute & Places Radius",
    settingsCommuteSectionSubtitle = "Settings for category-based reminders (supermarkets, etc.)",
    settingsMyCommuteRoute = "My usual commute route",
    settingsCommuteNotConfigured = "Not configured (Start ➔ Destination on map)",
    settingsTraceRoute = "Trace",
    settingsModifyRoute = "Modify",
    settingsClearRoute = "Clear",
    settingsPoiDetectionRadius = "Places Detection Radius",
    settingsPoiDetectionRadiusSubtitle = "Size of circular geofence around each place (POIs)",
    settingsPoiGlobalSearchRadius = "Global POI Search Radius",
    settingsPoiGlobalSearchRadiusSubtitle = "Maximum radius around you to search for places on Google Places",
    settingsRollingExitRadius = "Exit Buffer (Rolling Window)",
    settingsRollingExitRadiusSubtitle = "Distance traveled by car before automatically refreshing places ahead",
    settingsGeofenceCooldown = "Anti-rebound alert cooldown",
    settingsGeofenceCooldownSubtitle = "Minimum wait time before triggering again for a nearby place",
    settingsSmartFilter = "Smart Accessibility Filter",
    settingsSmartFilterSubtitle = "Ignores unreachable places (highway speed or opposite traffic direction)",
    settingsSmartFilterSpeedThreshold = "Highway transit speed threshold",
    settingsSmartFilterSpeedThresholdSubtitle = "Above this speed, local place alerts are filtered out",

    settingsSystemChannelsSectionTitle = "System Notifications",
    settingsSystemChannelsSectionSubtitle = "Default chimes for text-only reminders",
    settingsChannelTimeTitle = "Scheduled Reminders Channel (Time)",
    settingsChannelTimeSubtitle = "Sound, light and pop-up for scheduled times",
    settingsChannelPlaceTitle = "Geolocated Reminders Channel (Place)",
    settingsChannelPlaceSubtitle = "Sound, light and pop-up for GPS locations",
    settingsLogsSectionTitle = "Diagnostics & Logs",
    settingsLogsSectionSubtitle = "Technical history and reminder lifecycle traceability",
    settingsViewLogs = "View Event Logs",
    settingsViewLogsSubtitle = "Check creation steps, POIs, arming, and trigger events",
    settingsAccountSectionTitle = "Account & Session",
    settingsAccountSectionSubtitle = "Manage your Remindly profile",
    settingsConnectedAs = "Signed in as",
    settingsNotConnected = "Not signed in",
    settingsLogout = "Sign out",
    settingsLogoutConfirmTitle = "Sign out?",
    settingsLogoutConfirmMessage = "You will need to sign in again to sync your reminders."
)

fun getAppStrings(languageCode: String): AppStrings {
    return when (AppLanguage.fromCode(languageCode)) {
        AppLanguage.FRENCH -> FrenchStrings
        AppLanguage.ARABIC -> ArabicStrings
        AppLanguage.ENGLISH -> EnglishStrings
    }
}

fun getStringsForLanguage(languageCode: String): AppStrings = getAppStrings(languageCode)

val LocalAppStrings = staticCompositionLocalOf<AppStrings> {
    FrenchStrings
}
